# Generated by Django 3.2.7 on 2021-09-26 14:30

from django.db import migrations
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210926_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='password',
            field=mirage.fields.EncryptedCharField(max_length=20),
        ),
    ]
