# Generated by Django 3.2.7 on 2021-09-26 14:31

from django.db import migrations
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_appuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='password',
            field=mirage.fields.EncryptedCharField(max_length=255),
        ),
    ]
